### ISSUE TITLE
Add notes re: what JSDOM/jQuery is inaccurate

### ISSUE THREAD

**Issue by ItsJonQ** [helpscout/seed-barista#28]
Below are a list of issues encountered when testing. Not necessarily Barista's fault. Would be cool if Barista could somehow provide work arounds though.

---

**Doesn't correctly provide styles for `button` border**

```css
.btn { border: 1px solid red; }
```

```js
styles.mount();
styles.find('button.btn').prop('border');
// 2px outset buttonface
```

**Doesn't correctly account for specificity stacking**

It appears that either JSDOM or jQuery applies styles based on **when** they're specified in the compiled CSS.

```css
.btn.red { background: red; }
.btn-primary { background: blue; }
```

```js
styles.mount();
const $b = styles.find('button.btn.btn-primary');
$b.prop('background') // blue

$b.addClass('red');
$b.prop('background') // blue, but should be red
```

**Doesn't provide `$.height()`** calcuations
```css
.thing { padding: 50px; min-height: 10px; }
```

```js
styles.mount();
const $o = styles.find('.thing');
$o.height(); // 0px
```
