### ISSUE TITLE
Support for multiple selectors

### ISSUE THREAD

**Issue by riepladr** [helpscout/seed-barista#36]
Currently if there is a `.css` file like this:

```css
#main {
   margin: 0 auto;
}

p, li {
   color: white;
}

#main {
   background-color: black;
}

li {
   font-weight: bold;
}
```

It only takes the first selector when getting the `prop`. How can it be used to take the second selector (e.g. take the selector with the `font-weight: bold`)?
